name: build
channels:
  - conda-forge
  - mdtools
dependencies:
  # Base dependencies
  - python
  - pip
  - numpy
  - pyyaml

  # Conda build
  - anaconda-client
  - conda-build
  - boa

  # Machine learning dependencies
  - pytorch
  - lightning
  - opt-einsum

  # Visualization (for CLI)
  - cmap
  - networkx
  - open3d

  # PyPI build
  - pip:
    - build
    - twine
